### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by danboid** [a1291762/MoveFiles#1]
Could you please add build instructions to the README?

Thanks!

**Comment by a1291762** [comment]
I'm not sure what you want me to provide? This is an Android app, that builds with gradle (CLI) or Android Studio. There's nothing special or unique about it.

If you are new to Android, this guide may help, though you'll want to open this project rather than creating a new one.
https://developer.android.com/training/basics/firstapp/creating-project

**Comment by danboid** [comment]
I've never done any Android dev so it probably is obvious to any experienced Android dev how this is built but I think its always good practice to document how stuff is built even if it is only a case of typing `make && make install` (in the case of most UNIX-like C/C++ apps).
